### ISSUE TITLE
Add CPLD support

### ISSUE THREAD

**Issue by lorc** [xen-troops/rcar_flash#4]
Some of Renesas boards have CPLD accessible via USB serial port. It can be used to automatically switch a board into serial download mode.

**Comment by rshym** [comment]
Just proposal. What if we implement a few options to activate "SCIF Download Mode" via CPLD:
- `u-boot`;
- `binary` - use external binary. Need a better name for this option;
- auto - use `u-boot`, if we have a timeout, then use `binary`. Default option.

Both options need some logic to select x86/ARM cpld-control and command for 32/64 bit flash_writer.

**Comment by lorc** [comment]
I already implemented both SPI (for H3ULCB) and I2C (for S4/V3) protocols to control CPLD in Python. My implementation is ever better, because it restores previous USB TTY state (as opposed to `cpld-control` for ULCB). Now I need to integrate those tools into main `rcar_flash` script.

**Comment by lorc** [comment]
Closed via #10
